### ISSUE TITLE
th-desugar-1.7 fails to build with ghc-8.4.1 (Hackage bounds)

### ISSUE THREAD

**Issue by claudeha** [goldfirere/th-desugar#78]
The version bounds on Hackage are too loose, so my `cabal-install` tried to install `th-desugar-1.7` with `ghc-8.4.1` and failed with:

    Failed to install th-desugar-1.7

    [2 of 8] Compiling Language.Haskell.TH.Desugar.Reify ( Language/Haskell/TH/Desugar/Reify.hs, dist/dist-sandbox-953b16d5/build/Language/Haskell/TH/Desugar/Reify.o )
    
    Language/Haskell/TH/Desugar/Reify.hs:166:55: error:
        • Could not deduce (MonadIO (DsM q))
            arising from the 'deriving' clause of a data type declaration
          from the context: Quasi q
            bound by the deriving clause for ‘Quasi (DsM q)’
            at Language/Haskell/TH/Desugar/Reify.hs:166:55-59
          Possible fix:
            use a standalone 'deriving instance' declaration,
              so you can specify the instance context yourself
        • When deriving the instance for (Quasi (DsM q))
        |
    166 |   deriving ( Functor, Applicative, Monad, MonadTrans, Quasi
        |                                                       ^^^^^

I saw Hackage has `th-desugar-1.8` which claims to work with `ghc-8.4`, but `cabal-install` should have known that `th-desugar-1.7` would have failed and reported that at dependency resolution time.

Suggest making a revision on Hackage to constrain `base` version of `th-desugar-1.7` (and possibly other versions) to strictly below `ghc-8.4`'s `base-4.11`, or something else with similar effect.

**Comment by RyanGlScott** [comment]
Oops! I'd do this myself, but I don't have Hackage permissions for `th-desugar`.

To prevent this from happening in the future, I've restricted the upper version bounds for `template-haskell` in ddeaed0318058d3589b023fb63c286fb7e80badf.

**Comment by goldfirere** [comment]
@RyanGlScott what's your Hackage username? I tried RyanGlScott and RyanScott, but both failed.

**Comment by RyanGlScott** [comment]
It's ryanglscott.

**Comment by goldfirere** [comment]
@RyanGlScott, you're now a certified uploaded on Hackage. Congrats! :)

**Comment by RyanGlScott** [comment]
Thanks!

I've [revised](http://hackage.haskell.org/package/th-desugar-1.7/revisions/) `th-desguar-1.7`'s version bounds for `template-haskell` to have 2.13 as the upper bound, so this should be fixed now. (I also [revised](http://hackage.haskell.org/package/th-desugar-1.8/revisions/) `th-desugar-1.8` accordingly as well.)
