### ISSUE TITLE
DInstanceDs with explicit foralls no longer sweeten correctly under GHC HEAD (9.1)

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#151]
I discovered that the `th-desugar` test suite fails to compile on recent versions of GHC HEAD. Here is a somewhat minimized example of the phenomenon:

```hs
{-# LANGUAGE TemplateHaskell #-}
{-# OPTIONS_GHC -ddump-splices #-}
module Bug where

import Language.Haskell.TH
import Language.Haskell.TH.Desugar

class C a
data T a

$(do let a = mkName "a"
         dec = decToTH $ DInstanceD Nothing (Just [DPlainTV a ()]) [] (DConT ''C `DAppT` (DConT ''T `DAppT` DVarT a)) []
     pure [dec])
```

This compiles on GHC 9.0.1-alpha1 and earlier, but not on HEAD:

```
$ ~/Software/ghc-9.1.0.20201217/bin/ghc Bug.hs
Loaded package environment from /home/ryanglscott/Documents/Hacking/Haskell/staging/.ghc.environment.x86_64-linux-9.1.0.20201217
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o, Bug.dyn_o )
Bug.hs:(11,2)-(13,16): Splicing declarations
    do let a_a12Y = mkName "a"
           dec_a12Z
             = decToTH
                 $ DInstanceD
                     Nothing (Just [DPlainTV a_a12Y ()]) []
                     (DConT ''C `DAppT` (DConT ''T `DAppT` DVarT a_a12Y)) []
       pure [dec_a12Z]
  ======>
    instance forall a. C (T a)

Bug.hs:11:2: error:
    Instance head cannot contain nested ‘forall’s or contexts
    In an instance declaration
   |
11 | $(do let a = mkName "a"
   |  ^^^^^^^^^^^^^^^^^^^^^^...
```

Ultimately, I only have myself to blame here, since I simultaneously [added this feature to `th-desugar`](https://github.com/goldfirere/th-desugar/issues/118) and later [made it illegal in GHC with this patch](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4107) that restricts the use of nested `forall`s in instance heads. Apparently, the use of something like `` InstanceD Nothing [] (ForallT [PlainTV a ()] [] (ConT ''C `AppT` (ConT ''T `AppT` VarT a)) [] `` is close enough to a nested `forall` that GHC rejects it (even though it pretty-prints it as `instance forall a. C (T a)`). Sigh.

I now have to figure out how to dig my way out of the mess I created. Some possibilities:

* Patch GHC upstream so that `` InstanceD Nothing [] (ForallT [PlainTV a ()] [] (ConT ''C `AppT` (ConT ''T `AppT` VarT a)) [] `` doesn't trigger a nested `forall` warning.
* Remove the `Maybe [DTyVarBndr]` field from `DInstanceD`.

**Comment by goldfirere** [comment]
I'm afraid I like neither of your proposals. Can't you just change `decToTH` to do the right thing here, mapping the `Maybe [DTyVarBndr]` field to the right place in TH?

**Comment by RyanGlScott** [comment]
> Can't you just change `decToTH` to do the right thing here, mapping the `Maybe [DTyVarBndr]` field to the right place in TH?

The problem is that there [is no right place in TH](https://hackage.haskell.org/package/template-haskell-2.16.0.0/docs/Language-Haskell-TH.html#v:InstanceD):

```hs
data Dec
  = ...
  | InstanceD (Maybe Overlap) Cxt Type [Dec]
                                  -- ^ @{ instance {\-\# OVERLAPS \#-\}
                                  --        Show w => Show [w] where ds }@
```

**Comment by goldfirere** [comment]
So, is there no way to write, e.g.

```hs
instance forall (a :: Type -> Type). Eq (Proxy a)
```

in TH? That sounds like a TH bug.

**Comment by RyanGlScott** [comment]
Correct, there is no way to write that. But to be honest, I really can't be arsed to fix this bug, especially since it would inflict a disproportionate amount of pain to other TH users compared to the convenience it would provide. This is the reason I pursued [this hack](https://github.com/goldfirere/th-desugar/issues/151) in the first place.

**Comment by goldfirere** [comment]
What about just ignoring the contents of the `Maybe [DTyVarBndr]` field when converting to TH?

A good design guideline for th-desugar is that the th-desugar AST should be easier to *consume*, but not necessarily to *produce*. We thus prioritize consumption over production. Having a list of bound variables is useful for consumers, so I'd like to keep it. Ignoring it during conversion to TH isn't great for producers, but I care less about that use case.

What do you think?

**Comment by RyanGlScott** [comment]
> What about just ignoring the contents of the `Maybe [DTyVarBndr]` field when converting to TH?

That sounds reasonable to me.

**Comment by goldfirere** [comment]
OK. Let's make that the Official Plan.
